//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundTouch.Assets {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundTouch.Assets.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIR filter length not divisible by 8..
        /// </summary>
        internal static string Argument_CoefficientsFilterNotDivisible {
            get {
                return ResourceManager.GetString("Argument_CoefficientsFilterNotDivisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to set empty filter coefficients..
        /// </summary>
        internal static string Argument_EmptyCoefficients {
            get {
                return ResourceManager.GetString("Argument_EmptyCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive samplerate..
        /// </summary>
        internal static string Argument_ExcessiveSampleRate {
            get {
                return ResourceManager.GetString("Argument_ExcessiveSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal number of channels..
        /// </summary>
        internal static string Argument_IllegalNumberOfChannels {
            get {
                return ResourceManager.GetString("Argument_IllegalNumberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample-rate is too small to do beats detection..
        /// </summary>
        internal static string Argument_SampleRateTooSmall {
            get {
                return ResourceManager.GetString("Argument_SampleRateTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of channels not defined..
        /// </summary>
        internal static string InvalidOperation_ChannelsUndefined {
            get {
                return ResourceManager.GetString("InvalidOperation_ChannelsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients are not initialized..
        /// </summary>
        internal static string InvalidOperation_CoefficientsNotInitialized {
            get {
                return ResourceManager.GetString("InvalidOperation_CoefficientsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to overwrite the output pipe after it has been assigned..
        /// </summary>
        internal static string InvalidOperation_OutputPipeOverwrite {
            get {
                return ResourceManager.GetString("InvalidOperation_OutputPipeOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output pipe has not been assigned..
        /// </summary>
        internal static string InvalidOperation_OutputPipeUnset {
            get {
                return ResourceManager.GetString("InvalidOperation_OutputPipeUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output is undefined..
        /// </summary>
        internal static string InvalidOperation_OutputUndefined {
            get {
                return ResourceManager.GetString("InvalidOperation_OutputUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate not defined..
        /// </summary>
        internal static string InvalidOperation_SampleRateUndefined {
            get {
                return ResourceManager.GetString("InvalidOperation_SampleRateUndefined", resourceCulture);
            }
        }
    }
}
